spring:
 datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webtest?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username : root
    password : xz34567
 servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB


server:
  port: 8888

mybatis:
  type-aliases-package : com.ys.music.mapper
  mapper-locations : classpath:com/ys/music/mapper/*.xml

ftp:
  show : 192.168.20.96
  unit : 经同意
  location: D:/Git/
